on: [push, pull_request]
name: go test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.6]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: go vet
        run: go vet ./...
      - name: go test
        run: go test -v ./...
